version: '3.8'

services:
  api1:
    build: ./API1
    ports:
    - "5001:5000"

  api2:
    build: ./API2
    ports:
    - "5002:5000"

  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    depends_on:
    - api1
    - api2
